language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk-ea
matrix:
  allow_failures:
    - jdk: openjdk-ea
script:
  - ./scripts/test
after_success:
  - mvn clean -DforkCount=1 test jacoco:report coveralls:report

