/**
 * This file is automatically created by Recurly's OpenAPI generation process and thus any edits you
 * make by hand will be lost. If you wish to make a change to this file, please create a Github
 * issue explaining the changes you need and we will usher them to the appropriate places.
 */
package com.recurly.v3.requests;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import com.recurly.v3.Request;
import com.recurly.v3.resources.*;

public class BillingInfoCreate extends Request {

  @SerializedName("address")
  @Expose
  private Address address;

  /** Amazon billing agreement ID */
  @SerializedName("amazon_billing_agreement_id")
  @Expose
  private String amazonBillingAgreementId;

  /** Company name */
  @SerializedName("company")
  @Expose
  private String company;

  /** *STRONGLY RECOMMENDED* */
  @SerializedName("cvv")
  @Expose
  private String cvv;

  /** First name */
  @SerializedName("first_name")
  @Expose
  private String firstName;

  /** Fraud Session ID */
  @SerializedName("fraud_session_id")
  @Expose
  private String fraudSessionId;

  /**
   * An identifier for a specific payment gateway. Must be used in conjunction with `gateway_token`.
   */
  @SerializedName("gateway_code")
  @Expose
  private String gatewayCode;

  /**
   * A token used in place of a credit card in order to perform transactions. Must be used in
   * conjunction with `gateway_code`.
   */
  @SerializedName("gateway_token")
  @Expose
  private String gatewayToken;

  /**
   * The International Bank Account Number, up to 34 alphanumeric characters comprising a country
   * code; two check digits; and a number that includes the domestic bank account number, branch
   * identifier, and potential routing information
   */
  @SerializedName("iban")
  @Expose
  private String iban;

  /** *STRONGLY RECOMMENDED* Customer's IP address when updating their billing information. */
  @SerializedName("ip_address")
  @Expose
  private String ipAddress;

  /** Last name */
  @SerializedName("last_name")
  @Expose
  private String lastName;

  /** Expiration month */
  @SerializedName("month")
  @Expose
  private String month;

  /** Credit card number, spaces and dashes are accepted. */
  @SerializedName("number")
  @Expose
  private String number;

  /** PayPal billing agreement ID */
  @SerializedName("paypal_billing_agreement_id")
  @Expose
  private String paypalBillingAgreementId;

  /**
   * A token generated by Recurly.js after completing a 3-D Secure device fingerprinting or
   * authentication challenge.
   */
  @SerializedName("three_d_secure_action_result_token_id")
  @Expose
  private String threeDSecureActionResultTokenId;

  /**
   * A token [generated by
   * Recurly.js](https://developers.recurly.com/reference/recurly-js/#getting-a-token).
   */
  @SerializedName("token_id")
  @Expose
  private String tokenId;

  /**
   * An optional type designation for the payment gateway transaction created by this request.
   * Supports 'moto' value, which is the acronym for mail order and telephone transactions.
   */
  @SerializedName("transaction_type")
  @Expose
  private String transactionType;

  /** VAT number */
  @SerializedName("vat_number")
  @Expose
  private String vatNumber;

  /** Expiration year */
  @SerializedName("year")
  @Expose
  private String year;

  public Address getAddress() {
    return this.address;
  }

  /** @param address */
  public void setAddress(final Address address) {
    this.address = address;
  }

  /** Amazon billing agreement ID */
  public String getAmazonBillingAgreementId() {
    return this.amazonBillingAgreementId;
  }

  /** @param amazonBillingAgreementId Amazon billing agreement ID */
  public void setAmazonBillingAgreementId(final String amazonBillingAgreementId) {
    this.amazonBillingAgreementId = amazonBillingAgreementId;
  }

  /** Company name */
  public String getCompany() {
    return this.company;
  }

  /** @param company Company name */
  public void setCompany(final String company) {
    this.company = company;
  }

  /** *STRONGLY RECOMMENDED* */
  public String getCvv() {
    return this.cvv;
  }

  /** @param cvv *STRONGLY RECOMMENDED* */
  public void setCvv(final String cvv) {
    this.cvv = cvv;
  }

  /** First name */
  public String getFirstName() {
    return this.firstName;
  }

  /** @param firstName First name */
  public void setFirstName(final String firstName) {
    this.firstName = firstName;
  }

  /** Fraud Session ID */
  public String getFraudSessionId() {
    return this.fraudSessionId;
  }

  /** @param fraudSessionId Fraud Session ID */
  public void setFraudSessionId(final String fraudSessionId) {
    this.fraudSessionId = fraudSessionId;
  }

  /**
   * An identifier for a specific payment gateway. Must be used in conjunction with `gateway_token`.
   */
  public String getGatewayCode() {
    return this.gatewayCode;
  }

  /**
   * @param gatewayCode An identifier for a specific payment gateway. Must be used in conjunction
   *     with `gateway_token`.
   */
  public void setGatewayCode(final String gatewayCode) {
    this.gatewayCode = gatewayCode;
  }

  /**
   * A token used in place of a credit card in order to perform transactions. Must be used in
   * conjunction with `gateway_code`.
   */
  public String getGatewayToken() {
    return this.gatewayToken;
  }

  /**
   * @param gatewayToken A token used in place of a credit card in order to perform transactions.
   *     Must be used in conjunction with `gateway_code`.
   */
  public void setGatewayToken(final String gatewayToken) {
    this.gatewayToken = gatewayToken;
  }

  /**
   * The International Bank Account Number, up to 34 alphanumeric characters comprising a country
   * code; two check digits; and a number that includes the domestic bank account number, branch
   * identifier, and potential routing information
   */
  public String getIban() {
    return this.iban;
  }

  /**
   * @param iban The International Bank Account Number, up to 34 alphanumeric characters comprising
   *     a country code; two check digits; and a number that includes the domestic bank account
   *     number, branch identifier, and potential routing information
   */
  public void setIban(final String iban) {
    this.iban = iban;
  }

  /** *STRONGLY RECOMMENDED* Customer's IP address when updating their billing information. */
  public String getIpAddress() {
    return this.ipAddress;
  }

  /**
   * @param ipAddress *STRONGLY RECOMMENDED* Customer's IP address when updating their billing
   *     information.
   */
  public void setIpAddress(final String ipAddress) {
    this.ipAddress = ipAddress;
  }

  /** Last name */
  public String getLastName() {
    return this.lastName;
  }

  /** @param lastName Last name */
  public void setLastName(final String lastName) {
    this.lastName = lastName;
  }

  /** Expiration month */
  public String getMonth() {
    return this.month;
  }

  /** @param month Expiration month */
  public void setMonth(final String month) {
    this.month = month;
  }

  /** Credit card number, spaces and dashes are accepted. */
  public String getNumber() {
    return this.number;
  }

  /** @param number Credit card number, spaces and dashes are accepted. */
  public void setNumber(final String number) {
    this.number = number;
  }

  /** PayPal billing agreement ID */
  public String getPaypalBillingAgreementId() {
    return this.paypalBillingAgreementId;
  }

  /** @param paypalBillingAgreementId PayPal billing agreement ID */
  public void setPaypalBillingAgreementId(final String paypalBillingAgreementId) {
    this.paypalBillingAgreementId = paypalBillingAgreementId;
  }

  /**
   * A token generated by Recurly.js after completing a 3-D Secure device fingerprinting or
   * authentication challenge.
   */
  public String getThreeDSecureActionResultTokenId() {
    return this.threeDSecureActionResultTokenId;
  }

  /**
   * @param threeDSecureActionResultTokenId A token generated by Recurly.js after completing a 3-D
   *     Secure device fingerprinting or authentication challenge.
   */
  public void setThreeDSecureActionResultTokenId(final String threeDSecureActionResultTokenId) {
    this.threeDSecureActionResultTokenId = threeDSecureActionResultTokenId;
  }

  /**
   * A token [generated by
   * Recurly.js](https://developers.recurly.com/reference/recurly-js/#getting-a-token).
   */
  public String getTokenId() {
    return this.tokenId;
  }

  /**
   * @param tokenId A token [generated by
   *     Recurly.js](https://developers.recurly.com/reference/recurly-js/#getting-a-token).
   */
  public void setTokenId(final String tokenId) {
    this.tokenId = tokenId;
  }

  /**
   * An optional type designation for the payment gateway transaction created by this request.
   * Supports 'moto' value, which is the acronym for mail order and telephone transactions.
   */
  public String getTransactionType() {
    return this.transactionType;
  }

  /**
   * @param transactionType An optional type designation for the payment gateway transaction created
   *     by this request. Supports 'moto' value, which is the acronym for mail order and telephone
   *     transactions.
   */
  public void setTransactionType(final String transactionType) {
    this.transactionType = transactionType;
  }

  /** VAT number */
  public String getVatNumber() {
    return this.vatNumber;
  }

  /** @param vatNumber VAT number */
  public void setVatNumber(final String vatNumber) {
    this.vatNumber = vatNumber;
  }

  /** Expiration year */
  public String getYear() {
    return this.year;
  }

  /** @param year Expiration year */
  public void setYear(final String year) {
    this.year = year;
  }
}
