/**
 * This file is automatically created by Recurly's OpenAPI generation process and thus any edits you
 * make by hand will be lost. If you wish to make a change to this file, please create a Github
 * issue explaining the changes you need and we will usher them to the appropriate places.
 */
package com.recurly.v3.requests;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import com.recurly.v3.Request;
import com.recurly.v3.resources.*;

public class BillingInfoVerifyCVV extends Request {

  /** An identifier for a specific payment gateway. */
  @SerializedName("gateway_code")
  @Expose
  private String gatewayCode;

  /**
   * A token generated by Recurly.js after completing a 3-D Secure device fingerprinting or
   * authentication challenge.
   */
  @SerializedName("three_d_secure_action_result_token_id")
  @Expose
  private String threeDSecureActionResultTokenId;

  /**
   * A token [generated by
   * Recurly.js](https://recurly.com/developers/reference/recurly-js/#getting-a-token).
   */
  @SerializedName("token_id")
  @Expose
  private String tokenId;

  /** Unique security code for a credit card. */
  @SerializedName("verification_value")
  @Expose
  private String verificationValue;

  /** An identifier for a specific payment gateway. */
  public String getGatewayCode() {
    return this.gatewayCode;
  }

  /** @param gatewayCode An identifier for a specific payment gateway. */
  public void setGatewayCode(final String gatewayCode) {
    this.gatewayCode = gatewayCode;
  }

  /**
   * A token generated by Recurly.js after completing a 3-D Secure device fingerprinting or
   * authentication challenge.
   */
  public String getThreeDSecureActionResultTokenId() {
    return this.threeDSecureActionResultTokenId;
  }

  /**
   * @param threeDSecureActionResultTokenId A token generated by Recurly.js after completing a 3-D
   *     Secure device fingerprinting or authentication challenge.
   */
  public void setThreeDSecureActionResultTokenId(final String threeDSecureActionResultTokenId) {
    this.threeDSecureActionResultTokenId = threeDSecureActionResultTokenId;
  }

  /**
   * A token [generated by
   * Recurly.js](https://recurly.com/developers/reference/recurly-js/#getting-a-token).
   */
  public String getTokenId() {
    return this.tokenId;
  }

  /**
   * @param tokenId A token [generated by
   *     Recurly.js](https://recurly.com/developers/reference/recurly-js/#getting-a-token).
   */
  public void setTokenId(final String tokenId) {
    this.tokenId = tokenId;
  }

  /** Unique security code for a credit card. */
  public String getVerificationValue() {
    return this.verificationValue;
  }

  /** @param verificationValue Unique security code for a credit card. */
  public void setVerificationValue(final String verificationValue) {
    this.verificationValue = verificationValue;
  }
}
