#!/usr/bin/env bash
set -e

mvn clean compile

if [ ! -d ./bin ]; then
  mkdir -p ./bin;
fi

FORMAT=./bin/google-java-format-1.7-all-deps.jar
if test -f $FORMAT; then
    echo "Formatter file exists"
else
    curl -L https://github.com/google/google-java-format/releases/download/google-java-format-1.7/google-java-format-1.7-all-deps.jar > ./bin/google-java-format-1.7-all-deps.jar
fi
