#!/usr/bin/env bash

rm -f src/main/java/com/recurly/v3/Client.java
rm -f src/main/java/com/recurly/v3/QueryParams.java
rm -f src/main/java/com/recurly/v3/Constants.java
rm -f src/main/java/com/recurly/v3/requests/*
rm -f src/main/java/com/recurly/v3/resources/*
rm -f src/main/java/com/recurly/v3/exception/*
